version: "3"
services:
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=metrics-monitor
  zookeeper:
    ports:
      - "2181:2181"
    image: zookeeper:3.4
  kafka:
    ports:
      - "9092:9092"
    image: ches/kafka
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_IP=zookeeper
      - KAFKA_ADVERTISED_HOST_NAME=docker.for.win.localhost
  metrics-monitor-service:
    ports:
      - "8080:8080"
    image: 
    depends_on:
      - kafka
      - postgres
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://postgres:5433/metrics-monitor
      - KUMULUZEE_DATASOURCES0_USERNAME=postgres
      - KUMULUZEE_DATASOURCES0_PASSWORD=postgres
      - KUMULUZEE_LOGS_LOGGERS0_LEVEL=INFO
  metrics-monitor-angular-sample:
    ports:
      - "4200:4200"
    image:
