version: "3"

networks:
  access-host-net:
    external: true

services:
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metrics-monitor
    networks:
      - access-host-net

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - access-host-net

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - access-host-net

  metrics-monitor-service:
    ports:
      - "8080:8080"
    image: docker.mjamsek.com/metrics-monitor-service
    depends_on:
      - kafka
      - postgres
    environment:
      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://postgres:5433/metrics-monitor
      KUMULUZEE_DATASOURCES0_USERNAME: postgres
      KUMULUZEE_DATASOURCES0_PASSWORD: postgres
      KUMULUZEE_LOGS_LOGGERS0_LEVEL: INFO
      KUMULUZEE_STREAMING_KAFKA_PRODUCER_BOOTSTRAPSERVERS: kafka:9092
      KUMULUZEE_STREAMING_KAFKA_CONSUMER_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - access-host-net

  metrics-monitor-angular-sample:
    ports:
      - "4200:4200"
    image: docker.mjamsek.com/angular-sample
